### ISSUE TITLE
power_sensor_delay time issue

### ISSUE THREAD

**Issue by rmxs** [litinoveweedle/SmartIR#83] opened 2024-07-19 17:50 UTC
**Home Assistant version** 2024.7.2

**SmartIR version** 
1.18.0b1

`climate:
  - platform: smartir
    name: AC Bedroom
    unique_id: ac_bedroom
    device_code: 1070
    controller_data: remote.smart_ir1
    temperature_sensor: sensor.temp_sensor_bedroom_temperature
    humidity_sensor: sensor.temp_sensor_bedroom_humidity
    power_sensor_delay: 600
    power_sensor: sensor.ac_bedroom_status
    power_sensor_restore_state: true`

**Describe the bug**
I have set the power_sensor_delay to 600 but the time after the power sensor change from on to off or from off to on  is some seconds 1-2. I have try to change 600 to 6000 but same results.

**Expected behavior**
If you turn on or off the device from the remote the device have to response after xx seconds depends on  power_sensor_delay value

No logs produced, error, warning etc except 
`2024-07-19 20:39:27.175 DEBUG (MainThread) [custom_components.smartir.climate] Scheduled power sensor check for 'on' state
2024-07-19 20:39:27.176 DEBUG (MainThread) [custom_components.smartir.climate] Found 'cool' operation mode command.
2024-07-19 20:39:27.177 DEBUG (MainThread) [custom_components.smartir.climate] Found 'mid' fan mode command.
2024-07-19 20:39:27.177 DEBUG (MainThread) [custom_components.smartir.climate] convert temp '25' from '°C' to '°C' with 'None' precision.
2024-07-19 20:39:27.177 DEBUG (MainThread) [custom_components.smartir.climate] Input HA temperature '25°C' converted into device temperature '25.0°C'.
2024-07-19 20:39:27.177 DEBUG (MainThread) [custom_components.smartir.climate] convert temp '25' from '°C' to '°C' with '1' precision.
2024-07-19 20:39:27.177 DEBUG (MainThread) [custom_components.smartir.climate] Input HA temperature '25°C' closest found device temperature command '25°C' converts back into HA '25°C' temperature.
2024-07-19 20:39:27.178 DEBUG (MainThread) [custom_components.smartir.climate] Found '25', temperature command.`

**Comment by litinoveweedle** [comment] 2024-07-19 17:53
600 second delay for power sensors check? Why? Is you power sensors really taking so long (10 minutes) to reflect the real state of your controlled device? I think you probably misunderstand function of the power sensor

**Comment by litinoveweedle** [comment] 2024-07-19 17:56
If you really set power sensor delay for 10 minutes, than you have to wait 10 minutes after you switch device on/off to collect complete logs. Please describe in your own words what is your understanding of function of the power sensor.

**Comment by rmxs** [comment] 2024-07-19 18:04
I turn on the AC from remote, wait xx seconds depends on power_sensor_delay value and then the HA climate change state to on or off and send the last settings via IR if the restore_state_is true.
The power sensor or any other sensor have to be on or off for xxx seconds before any action!

**Comment by rmxs** [comment] 2024-07-19 18:16
> 600 second delay for power sensors check? Why? Is you power sensors really taking so long (10 minutes) to reflect the real state of your controlled device? I think you probably misunderstand function of the power sensor

No but i have a template that get the sensors watts and if watts more than 50 then state ON if less then OFF. Sometimes (maybe 1or 2 times per day) the AC units take a brake and stop draw power for some mins, that time the ac turns completly off.

Im using power sockets and brakers for all of AC units so the best way is to create a sensor that way

**Comment by litinoveweedle** [comment] 2024-07-19 18:27
> I turn on the AC from remote, wait xx seconds depends on power_sensor_delay value and then the HA climate change state to on or off and send the last settings via IR if the restore_state_is true. The power sensor or any other sensor have to be on or off for xxx seconds before any action!

This is not how it is working and how it is described in the docs. Without the power sensor the SmartIR only assumes the state of the AC unit (as it doesn't know if the IR command succeed or not to switch it on/off). So immediately if you switch device on/off via HA, then device change is reflect in HA disregarding true AC state. With power sensor, it works completely same - immediately after you switch device on/off the state is reflected to the HA state. In addition, power sensor check is scheduled X second to the future, to validate that device is really on or off. When check is executed HA indicated state of the AC is aligned to the state reflected by the sensor.

I use as well power socket indicating power consumption, but then I need to convert power consumption indicated by it into the dedicated switch entity. In my case 10sec is enough to reflect state of the AC unit.

So you description of the issue is invalid, as on/off state is reflected ALWAYS immediately. Only possible correction (in case you AC should be on but is not, or vice versa), should happen in the `power_sensor_delay` time.

**Comment by rmxs** [comment] 2024-07-19 18:27
> If you really set power sensor delay for 10 minutes, than you have to wait 10 minutes after you switch device on/off to collect complete logs. Please describe in your own words what is your understanding of function of the power sensor.

You are correct. The logs appeard after 10 mins but the commands for the following was send after 1-2 secs after power sensor change state.

`2024-07-19 21:19:13.970 DEBUG (MainThread) [custom_components.smartir.climate] Found 'cool' operation mode command.
2024-07-19 21:19:13.971 DEBUG (MainThread) [custom_components.smartir.climate] Found 'mid' fan mode command.
2024-07-19 21:19:13.971 DEBUG (MainThread) [custom_components.smartir.climate] convert temp '26.0' from '°C' to '°C' with 'None' precision.
2024-07-19 21:19:13.971 DEBUG (MainThread) [custom_components.smartir.climate] Input HA temperature '26.0°C' converted into device temperature '26.0°C'.
2024-07-19 21:19:13.971 DEBUG (MainThread) [custom_components.smartir.climate] convert temp '26' from '°C' to '°C' with '1' precision.
2024-07-19 21:19:13.971 DEBUG (MainThread) [custom_components.smartir.climate] Input HA temperature '26.0°C' closest found device temperature command '26°C' converts back into HA '26°C' temperature.
2024-07-19 21:19:13.971 DEBUG (MainThread) [custom_components.smartir.climate] Found '26', temperature command.`

**Comment by litinoveweedle** [comment] 2024-07-19 18:29
And BTW I use it this way and it works 100% ;-)

**Comment by rmxs** [comment] 2024-07-19 18:36
> And BTW I use it this way and it works 100% ;-)

And for me, it works until my AC units enter sleep mode for a few minutes and the power usage drops significantly. At that point, the template sensor changes from ON to OFF. This is why I'm trying to use the power_sensor_delay to delay the power-off command sent by SmartIR when the sensor switches to off.

**Comment by litinoveweedle** [comment] 2024-07-19 18:40
But what you describe is intended feature. If your power switch goes into 'off' then for the puspose of the SmartIR you device is 'off' and the HA state is aligned. So it works exactly as designed. Fix your power sensor to correctly differentiate between 'off' and 'sleep' states.

**Comment by litinoveweedle** [comment] 2024-07-19 18:43
This is not valid as the given config parameter `power_sensor_delay` is timer from the user triggering the change of the controlled device state, not delay in the power sensor state change. If you want to delay change of the power sensor state use automation for it. But it would probably open different can of worm. To get reliable function you need to fix your power sensor to correctly report real AC unit state. Closing as invalid.

**Closed by litinoveweedle** 2024-07-19 18:43 UTC
Labels: potential bug

**Comment by rmxs** [comment] 2024-07-19 18:45
> This is not valid as the given config parameter `power_sensor_delay` is timer from the user triggering the change of the controlled device state, not delay in the power sensor state change. If you want to delay change of the power sensor state use automation for it. But it would probably open different can of worm. To get reliable function you need to fix your power sensor to correctly report real AC unit state. Closing as invalid.


Maybe you are right, but please take into consideration the AC unit's sleep time, during which it doesn't draw any power (such as when the compressor is in sleep mode because it's too hot, etc.). I will try the automation + template sensor and fingers cross

**Comment by litinoveweedle** [comment] 2024-07-19 18:51
Again, fix sensor, or use different method establishing REAL state of the HVAC unit. My unit draw when in idle about 5W, setting power plug threshold to 3W works fine. Other use suggested using zigbee door contact mounted on the fan doors. when open it reports device as on. What you propose has no god programmatic solution. I will not be fixed insufficiency in your sensors by correcting its state based on some assumptions. Fix you sensor.
